name: Push package

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.1.201
    - name: Pack
      run: dotnet pack --configuration Release -o "./packages"
    - name: Publish NuGet
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_AUTH_TOKEN}}
      run: dotnet nuget push -s https://www.nuget.org/api/v2/package -k $NUGET_AUTH_TOKEN ./packages/*.nupkg --skip-duplicate
    - name: Publish GitHub
      run: dotnet nuget push -s https://nuget.pkg.github.com/drenalol/index.json ./packages/*.nupkg --skip-duplicate